### ISSUE TITLE
Tag release of docker image

### ISSUE THREAD

**Issue by bclermont** [cturra/docker-ntp#11]
https://hub.docker.com/r/cturra/ntp/tags

should have specific release tags to lock to a specific version

**Comment by cturra** [comment]
@bclermont thanks for the feedback!

tagging releases doesn't seem to be a common pattern with other docker projects that i've seen. this doesn't mean release tagging is right or wrong. i'm curious about the outcome you're hoping to achieve by having this as a feature? said differently, in your environment, what problem would this be solving for you?

**Comment by bclermont** [comment]
predictability of deployment

if you release a new version of the image that have changes in volume, configuration, environment, files, etc

then my deployment still work as I pinpoint to an older release and can upgrade when I want/need to

**Comment by ytechie** [comment]
@cturra I ask that you take a look at this again. It is considered a very bad practice to not tag these. It's the only container I'm running on my home server that isn't tagged.

Please take a look at this:
https://vsupalov.com/docker-latest-tag/
