### ISSUE TITLE
vars "NTP_SERVERS" not working

### ISSUE THREAD

**Issue by Panda12o8** [cturra/docker-ntp#13]
here is my docker-compose.yml file content
`
version: '3.4'

services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS="time.pool.aliyun.com"
`
the clock was not synced. so i checked the ntp peers and found the server name was "time*.google.com", clearly the var(NTP_SERVERS) was not setted gracefully.

**Comment by cturra** [comment]
@Panda12o8 i suspect you didn't build your updated docker container before running it. i just tested the docker-compose configuration you posted above and got the correct ntp server. here are the steps i ran in my local environment...

docker-compose file:
```
version: '3.4'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS="time.pool.aliyun.com"
```

build the image:
```
$> docker-compose build ntp
Building ntp
Step 1/6 : FROM alpine:latest
 ---> 965ea09ff2eb
Step 2/6 : RUN apk add --no-cache openntpd
 ---> Using cache
 ---> 3ebcc1b0a4f3
Step 3/6 : COPY assets/startup.sh /opt/startup.sh
 ---> 843a131edf9a
Step 4/6 : EXPOSE 123/udp
 ---> Running in 4bbd361a30e7
Removing intermediate container 4bbd361a30e7
 ---> d9b5cbabf325
Step 5/6 : HEALTHCHECK CMD ntpctl -s status || exit 1
 ---> Running in 018e3cc165e1
Removing intermediate container 018e3cc165e1
 ---> 0ffdb4b49233
Step 6/6 : ENTRYPOINT [ "/bin/sh", "/opt/startup.sh" ]
 ---> Running in 685196994cf7
Removing intermediate container 685196994cf7
 ---> 0406584c5ee1

Successfully built 0406584c5ee1
Successfully tagged cturra/ntp:latest
```

run container:
```
$> docker-compose up -d ntp
Creating ntp ... done
```

confirm ntp server:
```
$> docker exec ntp ntpctl -s peers
peer
   wt tl st  next  poll          offset       delay      jitter
182.92.12.11 time.pool.aliyun.com
    1  7  2    3s    9s       -45.494ms   189.700ms     2.742ms
```
