### ISSUE TITLE
Not running on ARM architecture (Odroid C2)

### ISSUE THREAD

**Issue by DanielOberlechner** [cturra/docker-ntp#16]
Hi,
I have the following docker-compose file:
version: '3.4'
services:
  ntp:
    #build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS=time.cloudflare.com

I tried to run it on my ArchLinux Odroid C2 Server but I always get the error:
`ntp    | standard_init_linux.go:211: exec user process caused "exec format error"`

Then I copied the same docker-compose file to my Macbook Pro and ran it there with Docker-Compose up and everything just worked out of the box.

I prefer using Docker-Compose instead of Dockerfile.
Is there any chance I can run my personal ntp server on the Odroid?
When I googled the error message I came across a post where someone has written that it is a architecture problem.

Am I only stupid and don't get it to run, or is my assumption true?
I'm new to Docker, so pardon me if I made a stupid mistake or if I don't get something right. But I think I 'understood' how docker should be running.

Kind regards,
Daniel Oberlechner

**Comment by cturra** [comment]
thanks for reaching out @DanielOberlechner and i'm sorry this container is not working for you on your odriod c2. unfortunately i have no way to reproduce this error myself so it may be difficult to come up with a solution for you.

let me think on this a little bit and get back to you. if i do make a chance, i will need help testing it. that may mean working from a branch in this repository - is that something you're comfortable doing?

do you have other containers successfully running on this odriod? and if so, do you by chance know if any of them are based on alpine linux?

**Comment by cturra** [comment]
@DanielOberlechner an update for you to test, when you have a moment. i've built a test container image that supports the following architectures: linux/amd64, linux/arm64 and linux/arm/v7. 

when you use the following image, it should automatically run the native version on your odriod c2 (assuming it's linux/arm64 or linux/arm/v7).

in your docker-compose file, can you update the image to `image: cturra/ntp-test:latest` and try running again?

**Comment by DanielOberlechner** [comment]
Hi cturra,
thank you for taking time to solve this problem!
I created a new image from cturra/ntp:latest but I get the same error.
I think that you got the wrong architecture.
The Odroid CPU is:
Amlogic S905 : Quad Core Cortex™-A53 (ARMv8 64bit) processor with Triple Core Mali-450 GPU
that means it is ARMv8 not v7 ...

I have the pihole running and a nginx instance.

Do you need further information?
How can I help you the best?

Greets from Italy,
Daniel :)

**Comment by cturra** [comment]
thanks for your help to test this change and i'm so happy to hear this new build process resolved the issue you were seeing.

for now, please feel free to continue to use the `ntp-test` container image on dockerhub. i need to re-tool a couple things on my end to build/push in the same way to the main ntp dockerhub project. once that's complete, i will reach out so you can verify that all worked as expected also.

i really appreciate your help! and greetings from Canada. 🇨🇦

**Comment by DanielOberlechner** [comment]
That's cool. I'm happy to help if I can! :)
Just let me hear if I can do help you.

Greets Daniel

**Comment by cturra** [comment]
@DanielOberlechner i have an update i'd love your assistance in testing. i have now created a new dockerhub repository for multi-architecture support. would you be able to update your `docker-compose` file to this new image and give it a restart for me?

`image: cturra/ntp-multiarch:latest`

if that works as expected for you, i will remove the ntp-test repository since that's not a super friendly name (it was afterall, just a test).

i have also updated the documentation around this if you want to give it a review:

 * https://hub.docker.com/repository/docker/cturra/ntp-multiarch

thanks again for all your help!

**Comment by DanielOberlechner** [comment]
Hi @cturra,
I've updated the image name and everything works like it should! :) 

One small thing I noticed:
The clock is now not synced and therefore it doesn't work yet.
You could add https://hub.docker.com/r/cturra/ntp here a small text,
and tell the people that it will work after some time?!

I tried ntpdate -qd <serverip> and it shows me the offset.

I guess it takes some time until everything is synchronized. 

Maybe some people will not get it instantly that everything works just fine.
But thats just my opinion, I guess it could help some folks out there ...

If you need more help don't hesitate to contact me. 

Kind regards,
Daniel :) 👍

**Comment by mkozjak** [comment]
@cturra - `cturra/ntp-multiarch:latest` seems to work on rpi3. Any thoughts on time sync @DanielOberlechner is talking about, though?

**Comment by cturra** [comment]
thanks for your patience with my reply @DanielOberlechner @mkozjak.

i suspect the flapping you're seeing over time with synchronization may be the results of using a single ntp server. if you update your `NTP_SERVERS` environment variable in your `docker-compose` file to use more than one ntp server, it may initially take a longer to get all the peers sychronized when you start the container, but probably will stay in sync since you have more endpoints to query. can you folks try using google's time servers again and report back?

snippet from docker-compose file:
```
environment:
      - NTP_SERVERS=time1.google.com,time2.google.com,time3.google.com,time4.google.com
```

**Comment by cturra** [comment]
just a heads up that there's been another issue opened to look into the skew that you both might be interested in checking out. see issue https://github.com/cturra/docker-ntp/issues/17 for some updates i have made. any assistance you can provide in testing would be wonderful!

note: i have not yet built the updated feature branch with multi-arch support, so it will only work on amd64 at the moment.
