### ISSUE TITLE
Server not stable for long

### ISSUE THREAD

**Issue by StefanWolf-tp** [cturra/docker-ntp#17]
Hey nice project!
it runs like a charm but i have the problem, that my server is not stable. I tried a lot of different ntp servers to sync with but even over an hour it is not stable. 
I started the server yesterday and even today when i checked the server was not stable:
just a few sudo docker exec ntp ntpctl -s status outputs within 5 minutes:
```
4/4 peers valid, clock unsynced, clock offset is 591.872ms
4/4 peers valid, clock unsynced, clock offset is 582.678ms
4/4 peers valid, clock unsynced, clock offset is 558.124ms
4/4 peers valid, clock unsynced, clock offset is 549.455ms
4/4 peers valid, clock unsynced, clock offset is -18161.083ms
4/4 peers valid, clock unsynced, clock offset is -18019.615ms
4/4 peers valid, clock unsynced, clock offset is -17914.237ms
4/4 peers valid, clock unsynced, clock offset is -16150.951ms
4/4 peers valid, clock unsynced, clock offset is -9582.942ms
```

sudo docker exec ntp ntpctl -s peers
```
peer
   wt tl st  next  poll          offset       delay      jitter
94.16.113.67 0.de.pool.ntp.org
    1  9  2   30s 3167s     -1710.079ms 11807.145ms  33665.677ms
78.46.253.198 1.de.pool.ntp.org
    1 10  2   22s   32s       580.689ms 10336.151ms  31168.227ms
162.159.200.1 2.de.pool.ntp.org
    1 10  3  730s 3287s    -16167.813ms    23.444ms     1.365ms
91.202.42.81 3.de.pool.ntp.org
    1  9  2  151s 3288s     -1709.630ms 11807.984ms  33665.965ms
```

what i have tried as servers so far:
- default (time.cloudflare.com)
- google (time1.google.com,time2.google.com,time3.google.com,time4.google.com)
- unspecific pool.ntp.org (pool.ntp.org)
- specific pool.ntp.org (0.de.pool.ntp.org,1.de.pool.ntp.org,2.de.pool.ntp.org,3.de.pool.ntp.org)

the unspecific pool.ntp.org worked the best so far - got a stable server after like 2 minutes but not for long.

Im running the docker container on an ubuntu 16.04 server - Docker version 18.09.3, build 774a1f4

hope someone got an idea.

**Comment by cturra** [comment]
hey @StefanWolf-tp, sorry to hear you're having issues with keeping your ntp clocks in sync. i can share some of my observations from what you've noted above (great detail by the way!), but am not entirely sure what can be done within this container to solve this. i believe it's the behaviour between your host (physical hardware) and openntpd service.

looking at the jitter from the output of your `peers` list shows some peers listing a really significant time difference. i would expect to see less than 10ms on each of those. my understanding is that if your clock is drifting too much (your clock offset suggests that's happening) ntpd can't keep up and will flip into a `clock unsynced` state until it can be corrected. that also explains the flapping you're seeing.

i have seen this myself, but definitely not on the same frequency as you've report nor with such a large drift from my peers. currently i am using time services from both cloudfare and google.

i apologize if i haven't offered up a solution, but will keep noodling on this to see if something further comes to mind. if you (or anyone else reading this) makes progress, please report back, i'd be great to hear what might be working for you.

cheers.

**Comment by cturra** [comment]
after spending some time thinking about the clock skew situation we're all seeing, i decided to try a different ntp service within the container. before i commit that work to master, it'd be awesome if i could have you (or anyone following along) give this update a try. so far my testing has gone really well and my clock has been much more stable - i'd be really interested in hearing if you have the same results.

to simplify your testing, i have gone ahead and created a temporary container image on docker hub that you can use: https://hub.docker.com/r/cturra/ntp-chrony 

here are the steps to get that up and running...

```
# pull from docker hub
$> docker pull cturra/ntp-chrony

# run ntp
$> docker run --name=ntp             \
              --restart=always       \
              --detach=true          \
              --publish=123:123/udp  \
              --cap-add=SYS_TIME     \
              cturra/ntp-chrony
```

thanks in advance for your assistance with this!

**Comment by StefanWolf-tp** [comment]
Hey huge thanks for helping!
i loaded and run the container. Works fine so far:
sudo docker exec ntp2 chronyc sources
```
210 Number of sources = 4
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^+ time01.nevondo.com            2   6    17    36   +515us[+1096us] +/-   65ms
^* isis.uni-paderborn.de         1   6    17    35   -896us[ -299us] +/-   25ms
^+ ntp.informatik.uni-breme>     2   6    17    35   +621us[+1213us] +/-   63ms
^+ dns02.xstream-labs.com        2   6    17    36   +909us[+1496us] +/-   47ms
```

sudo docker exec ntp2 chronyc tracking
```
Reference ID    : 83EA893F (isis.uni-paderborn.de)
Stratum         : 2
Ref time (UTC)  : Mon Mar 16 07:30:56 2020
System time     : 0.001087035 seconds slow of NTP time
Last offset     : -0.001118158 seconds
RMS offset      : 0.001118158 seconds
Frequency       : 17.815 ppm fast
Residual freq   : -0.262 ppm
Skew            : 60.956 ppm
Root delay      : 0.046326455 seconds
Root dispersion : 0.004932647 seconds
Update interval : 64.4 seconds
Leap status     : Normal
```

like you can see i get even lvl 2 stratum!

But one thing to mention. as you can see i named the docker container ntp2 cause i'm still running the "old" container - which seems to be stable as well since the weekend. 

sudo docker exec ntp ntpctl -s peers
```
peer
   wt tl st  next  poll          offset       delay      jitter
80.67.16.8 0.de.pool.ntp.org
    1 10  2   80s   95s       -36.629ms    26.266ms     2.842ms
213.239.239.165 1.de.pool.ntp.org
    1 10  2   75s   95s       -34.847ms    30.203ms     3.168ms
82.100.248.10 2.de.pool.ntp.org
    1 10  2    8s   93s       -35.471ms    25.979ms     1.894ms
88.198.17.248 3.de.pool.ntp.org
 *  1  2  3   26s  300s             ---- peer not valid ----
```


sudo docker exec ntp ntpctl -s status
`3/4 peers valid, clock synced, stratum 4`

**Comment by cturra** [comment]
@StefanWolf-tp thanks for the update and that's for sharing the details about running both containers together. i plan on waiting another day or so to let this change bake before merging this work into master. please keep me posted if you see anything odd.

good catch on the README updates on docker hub. i have the (docker hub) repository setup to auto build from github and it looks like my configuration allowed building from branches. as a result, the chrony branch was pulled in over master (oops). that has now been fixed permanency and the correct container build of master restored. thanks so much for reporting that to me 🙏

**Comment by cturra** [comment]
i wanted to take a moment to share that i've now merged this work back into master. both the github and dockerhub `ntp` repos are now up to date with this change and i've build/pushed the change to the `ntp-multiarch` container image also.

@StefanWolf-tp thanks so much for taking the time to do such a detailed report of your findings and assist in testing.

reference docker hub images:

 * ntp: https://hub.docker.com/repository/docker/cturra/ntp
 * ntp-multiarch: https://hub.docker.com/repository/docker/cturra/ntp-multiarch

**Comment by cturra** [comment]
... @StefanWolf-tp one quick follow up. once you've migrated back to the ntp container let me know and i will remove the temporary ntp-chrony one on dockerhub?

**Comment by StefanWolf-tp** [comment]
you can remove the ntp-chrony. i did not used any of them on a productive system so far. but thanks for your help and energy - great work
