### ISSUE TITLE
What does this ntp set the time of?

### ISSUE THREAD

**Issue by ForceConstant** [cturra/docker-ntp#24]
So typically you run ntp to set the time of the computer. So does running this in a container affect the time of the docker host, or the other containers? 

If not what is the use case for this, as a ntp relay?

**Comment by cturra** [comment]
this container can be used to run an ntp server within your network. it syncs with public ntp servers over the internet and devices (computers) you run could connect to it to keep their clocks in sync.

here is a good article on why you may want to run your own ntp server(s)

 => https://weberblog.net/why-should-i-run-own-ntp-servers/
