### ISSUE TITLE
how can i set container so that it does not uses any exteranl internet ntp servers. 

### ISSUE THREAD

**Issue by ajit-hi** [cturra/docker-ntp#25]
how can i set container so that it does not uses any exteranl internet ntp servers(like I dont want to use servers like time.cloudfare.com). What I want is that I will manually set time of my host and then all ntp clients of my host should synchronise with that time.
For example I want my time to 10 days behind utc. 

Without docker I was able to do this by setting the server directive for ntp as (127.127.1.0),intead of ntp.ubuntu.com. So the ntp server do not syncs time with ntp.ubuntu.com, it only sends to client what time is available on server itself.

**Comment by cturra** [comment]
hey @ajit-hi - i think there are a couple questions packed into here. i will do my best to address both of them.

1. you should be able to select any time server you'd like, public or private, but specifying them in the `NTP_SERVERS` environment variable when starting this container. details on how to do that can be found at => https://github.com/cturra/docker-ntp#configure-ntp-servers

2. connecting to 127.127.1.0? from within the docker container any 127.0.0.0/8 address will likely not attempt to leave the container (the OS in that container would try to route those requests to itself -- locally). my guess is you'll need to use the IP address of your host machine to hit that ntp service. this is probably another RFC1918 address in the 192.168.0.0/16, 172.16.0.0/12 or 10.0.0.0/8 ranges.

good luck! and keep me posted on how you make out.

**Comment by ajit-hi** [comment]
Thank you Chris. What i did was to comment out all external pool servers from chrony.conf and added a line 'local stratum 10'. This seems to work fine.
