### ISSUE TITLE
container doesn't start in a unprivileged lxc container

### ISSUE THREAD

**Issue by Rinus79** [cturra/docker-ntp#28]
My docker environment is running in an unprivilged lxc container.
When I try to run docker-ntp I receive following error. 
ntp    | 2020-12-27T09:09:51Z chronyd version 3.5.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS -SECHASH +IPV6 -DEBUG)
ntp    | 2020-12-27T09:09:51Z Fatal error : adjtimex(0x8001) failed : Operation not permitted

####
 cturra/ntp:latest              "/bin/sh /opt/startu…"   13 seconds ago   Restarting (1) 4 seconds ago 

Do you have a hint?

**Comment by cturra** [comment]
@Rinus79 i'm sorry to hear that you're having troubles with this container. unfortunately, it was never been tested on lxc so i cannot provide assistance at this time, but maybe someone else in the community can? all my testing and running of this container over the years has been done in docker.

however, with that said, based on the error message you've shared, it looks like you cannot modify global system time with an unprivileged lxc container.

**Comment by cturra** [comment]
closing this issue for now. @Rinus79 do keep us posted if you learn anything interesting you'd like to share.
