### ISSUE TITLE
missing multi arch builds in docker hub

### ISSUE THREAD

**Issue by morrisalex** [cturra/docker-ntp#33]
Host: Raspberry Pi 4
OS: Ubuntu Server 20.04.1 LTS (aarch64)

This morning I tried to update my cturra/ntp container from image ID 7d5219fcd338 to 6deea110137f. The previous image launched a container just fine and was happily providing NTP services to my network.

The new image won't launch a container. It throws the error message "standard_init_linux.go:219: exec user process caused: exec format error"

Googling that message suggests that this error is likely caused by trying to run an image intended for a different architecture. But I'm not doing anything different than I did with the previous image.

The page at https://hub.docker.com/r/cturra/ntp indicates that "linux/arm64" is among the supported architectures for this image.

I'm still finding my feet with Docker, so I'm open to the possibility that I'm doing something daft without realising, but I can't work out what. The previous image worked; the current image doesn't. And I'm stumped.

Any suggestions, or clue-by-fours?

**Comment by cturra** [comment]
@morrisalex you're absolutely right! it looks like the only image that was available in docker hub was for the linux/amd64 architecture. a couple days ago i was playing around with updating my build environment and i must have made a mistake along the way, i did some basic testing, but clearly didn't catch this. i have re-pushed the multi-architecture builds, so you should be sorted. do you mind giving this a test for me again?

i want to also thank-you so much for opening this issue to let me know and take a moment to apologize for the time you wasted getting to the bottom of this. 🙏🏼

**Comment by morrisalex** [comment]
Bingo! That did the trick. I pulled down the latest image (02e64555bdbf) and it successfully spun up a container as expected.

Thanks very much for fixing this.

**Comment by cturra** [comment]
awesome. thanks for the update @morrisalex. i will go ahead and close this issue.
