### ISSUE TITLE
How do I change the time sync interval?

### ISSUE THREAD

**Issue by King-of-penguins** [cturra/docker-ntp#37]
The server accesses IP address 162.159.200.1 (time.cloudflare.com) every 64.5 seconds.
How can I increase the time synchronization interval? So that the time is synchronized (with the remote Cloudflare server) every 10 minutes.

**Comment by King-of-penguins** [comment]
Apologies for my hasty question. When I first installed docker-ntp, the sync interval was 64.5 seconds. Now, a few hours later, is 825 seconds or more.

**Comment by cturra** [comment]
hey, no problem! the behaviour you've described above is what i would expect - chronyd will initially have a short polling interval to ensure the clock doesn't get too much skew, then back off the frequency over time.

with this said, i just wanted to circle back with you to see if you were comfortable having this issue closed? while these polling intervals can be manipulated, i don't think, in general they're best to touch.

**Comment by King-of-penguins** [comment]
Now polling time is 1027 seconds (~17 minutes). For me, this is a very normal polling time. So I close this question.

**Comment by cturra** [comment]
thanks for circling back with your feedback! 👍🏼
