### ISSUE TITLE
listen udp4 0.0.0.0:123: bind: address already in use. (Docker MacOS only)

### ISSUE THREAD

**Issue by lucantolinos** [cturra/docker-ntp#38]
Hello,
We are using the docker-ntp projects for month but recently we got this issue:

With the command:
> docker run --name=ntp            \
>               --restart=always      \
>               --detach              \
>               --publish=123:123/udp \
>               cturra/ntp

We got the following error message : 
docker: Error response from daemon: driver failed programming external connectivity on endpoint ntp (4a4b3c16599cea9cee1802fffc845b7bdb0517e656e05fa1ad2e7ff5e021c63a): Error starting userland proxy: listen udp4 0.0.0.0:123: bind: address already in use.

this happens only on docker Mac version >= v3.2.0 (tested on all the version >= 3.2.0. Up to now, the docker-ntp was working with no problem on Mac and Linux. If I downgrade to 3.1.0 on Mac it works. Of course, i'v checked that I have 
I suppose that this problem is related only to the docker engine on Mac and has nothing to do with the docker-ntp project, but before opening an issue in the docker Mac project, is there anything is miss ? I there additional rights or flags to start this container ?

Thank you for your help.
++

**Comment by cturra** [comment]
i'm sorry to hear you're having a rough time, but thank-you for reaching out and providing such good details.

best i can tell from your description this is indeed environmental with your docker desktop on mac. i gave this a test myself and wouldn't you know it, i too am running into the same issue you've described! my local machine is running macos 11.2.3 on  Intel hardware. i saw you opened an issue upstream with the docker/for-mac project, so have added my own comment to it (thanks for doing that btw!)

just to connect these together, for folks who may end up here, you can find the upstream issue at:

 * https://github.com/docker/for-mac/issues/5589

for completeness, here are the comments i left in the upstream issue:

[...] i get the same results with both docker desktop on mac 3.3.1 and 3.3.0. here are the steps to reproduce from my environment (macos 11.2.3; Intel).

fetch container:
```
$ docker pull cturra/ntp
Using default tag: latest
latest: Pulling from cturra/ntp
Digest: sha256:138d7cace3bab5113a5944fdae10e91e406bfa0f0fe013afd908eee09839a147
Status: Image is up to date for cturra/ntp:latest
docker.io/cturra/ntp:latest
```

launch:
```
$ docker run --name=ntp --detach --publish=123:123/udp cturra/ntp
efdd358c3e4b6f11e7ff269afac3104a61512d2a28caf0a3b52307a5050015c8
docker: Error response from daemon: driver failed programming external connectivity on endpoint ntp (c82dc97659eb46289f368d20e89a094ad96bb429f770762e79a31f221282c168): Error starting userland proxy: listen udp4 0.0.0.0:123: bind: address already in use.
```

confirm port not in use:
```
$ sudo lsof -i :123 | echo $?
1

$ netstat -anp udp | awk '{print $4}' | grep 123 | echo $?
1
```

**Comment by cturra** [comment]
this issue has now been resolved upstream in docker desktop for mac in version 3.3.2 (63878). 🎉

**Comment by lucantolinos** [comment]
Ok for me, works flawless now.
Thank you.
++
