### ISSUE TITLE
Suppression of the master branch leads to integration issues.

### ISSUE THREAD

**Issue by ncarrier** [cturra/docker-ntp#41]
Hello,
Apparently, the main branch has been suppressed (and renamed to main?).
This causes issues in CI systems which track the master branches.
Would it be possible to restore the master branch or at least, to create version tags?

**Comment by cturra** [comment]
sorry for any inconvenience this has caused, but i decided to replace the `master` branch with `main` to ensure we're providing an inclusive community for this project.

**Comment by ncarrier** [comment]
Ok, why not.
But what about creating version tags?
