### ISSUE TITLE
ntp in docker swarm

### ISSUE THREAD

**Issue by JudahMorrison** [cturra/docker-ntp#50]
I am trying to spin up this ntp server in a docker swarm. The container is never able to spin up even though it works locally.
![image](https://user-images.githubusercontent.com/66790728/170111317-fde0bf44-c0b9-41b7-8d64-8773f6c93de5.png)

**Comment by cturra** [comment]
sorry to hear this container isn't working in your docker swarm cluster. to better understand what's going on, can you grab logs from one of the containers that's not going healthy and share here?

```
docker service logs -f {NAME_OF_THE_SERVICE}
```

**Comment by JudahMorrison** [comment]
Thanks for the quick response!

I found the problem. To get the container to work in the swarm you must remove/comment out "read_only: true" from the docker-compose.yml.

**Comment by cturra** [comment]
thanks for confirming and i'm glad to hear your on track. 🤘🏼 

i had suspected that was what was going on, but am not entirely sure why. it might be worth adding a note to the main README around this, i will take a stab at that.
