### ISSUE TITLE
Docker Hub push?

### ISSUE THREAD

**Issue by ptruman** [cturra/docker-ntp#55]
Hi

Has this been rebuilt?
Docker advises a new push 6 days ago but I can't see any changes here?

https://hub.docker.com/r/cturra/ntp shows an update 6 days ago (6th Dec) but no changes in src?

**Comment by cturra** [comment]
hey @ptruman - that's correct, last week i pushed a new build of this container up to docker hub.

there were no feature changes, but i did want to grab several of the latest dependent packages, like alpine linux 3.17.0 to ensure we're staying on top of security patching. 

if it's helpful, you can find some details around the build information in the container labels. here is an example of how you can look at that information directly:

```bash
$> docker inspect --format='{{.Config.Labels.build_info}}' ntp
cturra/docker-ntp build-date:- 2022-12-06T23:47:09+0000
```

**Comment by ptruman** [comment]
Cool. Thanks for confirming :)
