### ISSUE TITLE
[Feature request] possiblity to sync system clock and not have default ntp server.

### ISSUE THREAD

**Issue by Gontier-Julien** [cturra/docker-ntp#56]
Hi!
Just wanted to know if it would be possible to add an environment variable to be able to sync the system clock from the docker container?
I know it was taken off to have it as not a privilege container. But it would be great to have the option if we want.
My reason, i run chrony as both my client and server on my server, so i kinda don't want to have 2 chrony process if possible ^^'

Secondly i wanted to know if by setting a volume (read-only) to the chrony.conf, with my own conf file, if it would be overwritten with the default ntp server?
Correct me if i'm wrong but it shouldn't be able to modify it, if it is mounted as read-only right?

**Comment by Gontier-Julien** [comment]
Also unrelated to this issue, but is the build: . variable needed on the docker compose? I'm asking because it the first time seeing it x)

**Comment by cturra** [comment]
hey @Gontier-Julien thanks for reaching out. see my comments inline below.

> Just wanted to know if it would be possible to add an environment variable to be able to sync the system clock from the docker container?

the only way to do this would be to give the container 'privileged' access to your system. the point of this container in the first place was to run NTP without requiring privileged access and i feel strongly about not changing that position for this project. doing so is generally unsafe.

> Secondly i wanted to know if by setting a volume (read-only) to the chrony.conf, with my own conf file, if it would be overwritten with the default ntp server?

setting the file system to read-only was to accomplish 2 things: 1) slightly faster startup times and (2) hardening the container. 

when this container launched, the chrony.conf file is dynamically generated by the startup script, found below. any changes you might manage to make to it will not persist unless you fork and add those do this script.

  * https://github.com/cturra/docker-ntp/blob/main/assets/startup.sh

> Also unrelated to this issue, but is the build: . variable needed on the docker compose? I'm asking because it the first time seeing it x)

only required if you want to use `docker compose build ...`

**Comment by Gontier-Julien** [comment]
Seem fair and logical!
So could I make a fork of this project and/or would you be able to create a container in co existence of this one with the rtcsync capability?

It would be great for many peoples I guess, because it seem to be the only chrony container to be properly maintained (kudo and thank for that btw) ^^

**Comment by cturra** [comment]
thanks for your patience with my reply, i somehow missed your last message.

i would prefer not to maintain a fork of this that allows the container to run with 'privileged' access to the host since this might get confusing for users. and again, my original intentions for this project were to *not* require any privileged capabilities to run the clock in a container.

i'm not trying to suggest you're approach is incorrect, but it might be better to run a local ntp service on your host machine that grabs it's time from the container (and an Internet source as backup). this is actually what i do and suspect most of the millions of users this container have done the same.

**Comment by Gontier-Julien** [comment]
no worry's !
Maybe would it be possible to have an option to disable the startup script? So a read-only volume for the config file could be mounted to it without getting overwritten?
I think i might do the same as your setup

**Comment by cturra** [comment]
again, coming back to the intent, this container is meant to be immutable. so configuration changes remaining after a restart would break that.

with the above said, are there particular capabilities you're looking to be able to set yourself within the chrony config? maybe they can be passed as environment variables.

**Comment by Gontier-Julien** [comment]
That my current config without rtcsync, maxupdateskew and makestep.
I don't know if leapsectz is still needed tho
```
# Welcome to the chrony configuration file. See chrony.conf(5) for more
# information about usable directives.

#Global
server time.cloudflare.com iburst nts
server time.euro.apple.com iburst
server time.apple.com iburst
server time.facebook.com iburst
#Netherland
server nts.netnod.se iburst nts
server ntppool1.time.nl iburst nts
server ntppool2.time.nl iburst nts
#Germany
server ptbtime1.ptb.de iburst nts
server ptbtime2.ptb.de iburst nts
server ptbtime3.ptb.de iburst nts
#Switzerland
server ntp.zeitgitter.net iburst nts
server ntp.trifence.ch iburst nts

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Save NTS keys and cookies.
ntsdumpdir /var/lib/chrony

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location.
#logdir /var/log/chrony

# Get TAI-UTC offset and leap seconds from the system tz database.
# This directive must be commented out when using time sources serving
# leap-smeared time.
leapsectz right/UTC

# You might want the computer to be an NTP server for other computers.
#
# By default, chronyd does not allow any clients to access it.  You need
# to explicitly enable access using 'allow' and 'deny' directives.
#
# e.g. to enable client access from the 192.168.*.* class B subnet,

allow 192.x.x.x/24

# Normally, chronyd will keep track of how many times each client
# machine accesses it.  The information can be accessed by the 'clients'
# command of chronyc.  You can disable this facility by uncommenting the
# following line.  This will save a bit of memory if you have many
# clients and it will also disable support for the interleaved mode.

noclientlog
```

**Comment by Gontier-Julien** [comment]
So the only thing that i seem to miss and idk how to get it on the container, is:
`noclientlog` , the ability to connect to nts sources, and to allow only clients from a specfic class subnet.

Ps: btw since the server doesn't sync the system clock, there is no need to ` rtcsync` in the config file.

**Comment by cturra** [comment]
this is great! thanks for the follow up.

i have proposed a change over in the [`noclientlog`](https://github.com/cturra/docker-ntp/tree/noclientlog) branch if you want to give it a test run for me? the idea is you can pass a `NOCLIENTLOG=true` environment variable to the container and it will set the chronyd configuration appropriately at launch.

quick steps to test after you've cloned this repo (and jumped into the branch) are...

```
# build a container image
$> ./build.sh

# update the NOCLIENTLOG option in the vars file
$> vim vars

# run the container
$> ./run.sh

# verify config
$> docker exec -ti ntp cat /etc/chrony/chrony.conf
```

let me know how you make out and i will get a pull request cut. also, thanks so much for your contributions @Gontier-Julien!

**Comment by Gontier-Julien** [comment]
It work as excepted! And good to merge for me!

**Comment by Gontier-Julien** [comment]
Now before i can close this issue, how can i get `NTS` working on the container?
I think it would be quite nice to have it (if it not possible in the current state) with the next update of the container.

**Comment by Gontier-Julien** [comment]
Another suggestion is, i don't know if `linux/386` is still useful to build. It now unsupported by linux anyway and i doubt there is anyone using it.

**Comment by cturra** [comment]
> Now before i can close this issue, how can i get `NTS` working on the container? I think it would be quite nice to have it (if it not possible in the current state) with the next update of the container.

let's pull that into a different conversation. the basic config isn't difficult, but would pull in a bunch more requirements around certificate generation, etc. i need to think more about that.

**Comment by cturra** [comment]
> It work as excepted! And good to merge for me!

can you please give PR https://github.com/cturra/docker-ntp/pull/57 a quick review and comment for me?

**Comment by Gontier-Julien** [comment]
> > Another suggestion is, i don't know if `linux/386` is still useful to build. It now unsupported by linux anyway and i doubt there is anyone using it.
> 
> fwiw - according to the stats from docker hub, the linux/386 image does get pulled. in fact, it was last pulled 33 minutes ago.

I actually didn't expect that! Interesting!

**Comment by Gontier-Julien** [comment]
> > Now before i can close this issue, how can i get `NTS` working on the container? I think it would be quite nice to have it (if it not possible in the current state) with the next update of the container.
> 
> let's pull that into a different conversation. the basic config isn't difficult, but would pull in a bunch more requirements around certificate generation, etc. i need to think more about that.

Alright no problem!

**Comment by Gontier-Julien** [comment]
Closing this now that #57 is added.
