### ISSUE TITLE
[Feature request] Ability to use NTS servers.

### ISSUE THREAD

**Issue by Gontier-Julien** [cturra/docker-ntp#58]
As the tittle say.

It would be nice to use NTS servers with the docker container.
This would improve security and most well known NTP server is capable of NTS such as Cloudflare.

RFC link: [https://www.rfc-editor.org/rfc/rfc8915](https://www.rfc-editor.org/rfc/rfc8915)

**Comment by gaby** [comment]
👍🏻 for adding this feature
