### ISSUE TITLE
thousands of ptr requests per day

### ISSUE THREAD

**Issue by adriadam10** [cturra/docker-ntp#68]
inspecting my dns log i have found that there are a lot ptr requests to the ip of time.cloudflare.com.
Is this normal?
![image](https://github.com/cturra/docker-ntp/assets/57327458/57549ab7-18c9-4ba2-afcf-364091c27839)

**Comment by cturra** [comment]
that's an interesting discovery. i have not been able to reproduce this locally in my environment with the latest ntp container image (which includes the latest chroyd stabel release). it's worth pointing out, that this container doesn't do anything overly clever... it's simply wrapping chronyd. so, if you believe there is in fact an issue here, i see 2 options:

1) use a different upstream ntp server... personally, i try to use stratum 1 servers, so don't typically use time.cloudflare.com
2) reach out to the chronyd community to see if there's a known issue here

please do keep me posted on what you find out, if anything... i am curious.

**Comment by cturra** [comment]
awesome find! thanks for your contribution 🎉
